# Generated by Django 3.2.9 on 2021-11-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.CreateModel(
            name='ProductPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Активен'), ('draft', 'Доработка'), ('check', 'Проверяется'), ('hidden', 'Скрыт')], default='check', max_length=20, verbose_name='Статус')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес порции')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='restaurants.product')),
            ],
            options={
                'unique_together': {('product', 'weight', 'price')},
            },
        ),
    ]
