# Generated by Django 3.2.9 on 2021-11-30 14:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0002_auto_20211128_1706'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='restaurant',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='closes_in',
            new_name='close_time',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='opens_in',
            new_name='open_time',
        ),
        migrations.AddField(
            model_name='productportion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_portions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productportion',
            name='discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_time',
            field=models.PositiveSmallIntegerField(default=90, null=True, verbose_name='Время доставки'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='self_pickup_discount',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Скидка на самовывоз'),
        ),
    ]
